#!/bin/bash

echo "Creating Repository : $1"
source .env
python create.py $1
cd $FILEPATH$1
git config --global init.defaultBranch main
git init
git remote add origin https://github.com/$USERNAME/$1.git
echo "# $1 : ginit made it!" >> README.md
git add .
git commit -m "Initial Commit"
git push -u origin main
